# Generated by Django 4.1.6 on 2023-04-13 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mymovdb_movieinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=300, unique=True)),
                ('releaseyear', models.CharField(default='', max_length=4)),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('poster', models.CharField(default='', max_length=500)),
                ('genres', models.CharField(default='', max_length=500)),
                ('runtime', models.IntegerField(default=0)),
                ('budget', models.BigIntegerField(null=True)),
                ('revenue', models.BigIntegerField(null=True)),
                ('production_companies', models.CharField(default='', max_length=1000)),
                ('tagline', models.CharField(default='', max_length=1000)),
                ('backdrop_path', models.CharField(default='', max_length=1000)),
                ('vote_average', models.FloatField(null=True)),
                ('director', models.CharField(default='', max_length=300)),
                ('actors', models.CharField(default='', max_length=1000)),
                ('writers', models.CharField(default='', max_length=1000)),
                ('producers', models.CharField(default='', max_length=1000)),
                ('int_id', models.PositiveIntegerField(null=True, unique=True)),
                ('pull_id', models.PositiveIntegerField(null=True, unique=True)),
            ],
            options={
                'db_table': 'mymovdb_movieinfo',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='movdb.mymovdb_movieinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movdb.mymovdb_movieinfo')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movdb.userprofile')),
            ],
        ),
    ]
